/*
 * faasnap
 *
 * FaaSnap API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Vm1 struct {
	FuncName string `json:"func_name,omitempty"`
	SsId string `json:"ssId,omitempty"`
	Namespace string `json:"namespace,omitempty"`
}
